version: '2'

services:
    project:
        build: ./docker-files/project
        container_name: home-framework-project
        depends_on:
            - postgresql
        volumes:
            - .:/var/www
        ports:
             - 8000:80

    postgresql:
        image: postgres:9.5.6
        container_name: home-framework-postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test
        volumes:
            - /var/lib/postgresql
