version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - .:/app
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
        depends_on:
              - 'php-fpm'
    php-fpm:
        build: docker/php
        ports:
          - 9000
        volumes:
          - .:/app
    postgres10:
      image: postgres:10
      ports:
       - '5432:5432'
      volumes:
       - .:/app
       - data:/var/lib/postgresql/data
volumes:
  data: {}